name: flutter_iconica_utilities
description: Iconica utility package with all kinds of utility functions
version: 0.0.4
homepage: iconica.nl

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
